### ISSUE TITLE
ValueError: The last dimension of the inputs to `Dense` should be defined. Found `None`.

### ISSUE THREAD

**Issue by juyee1698** [JakeNims1305/DataScienceMusic#1]
I get a value error regarding the Dense layer while training. My Keras version is 2.4.3
I can't figure out what's the problem. Please help.

**Comment by robgon-art** [comment]
I'm getting the same thing in model.fit()

`    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:806 train_function  *
        return step_function(self, iterator)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:796 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:1211 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:2585 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:2945 _call_for_each_replica
        return fn(*args, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:789 run_step  **
        outputs = model.train_step(data)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:747 train_step
        y_pred = self(x, training=True)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py:985 __call__
        outputs = call_fn(inputs, *args, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:386 call
        outputs = layer(inputs, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py:982 __call__
        self._maybe_build(inputs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py:2643 _maybe_build
        self.build(input_shapes)  # pylint:disable=not-callable
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/core.py:1168 build
        raise ValueError('The last dimension of the inputs to `Dense` '

    ValueError: The last dimension of the inputs to `Dense` should be defined. Found `None`.`

**Comment by robgon-art** [comment]
It seems to be related to the SeSelfAttention layers. If you comment them out, it seems to work:

#create the structure of the neural network
model = Sequential()
model.add(Bidirectional(LSTM(512,
    input_shape=(network_input.shape[1], network_input.shape[2]), #n_time_steps, n_features?
    return_sequences=True)))
'# model.add(SeqSelfAttention(attention_activation='sigmoid'))
model.add(Dropout(0.3))

model.add(Bidirectional(LSTM(512,return_sequences=True)))
'# model.add(SeqSelfAttention(attention_activation='sigmoid'))
model.add(Dropout(0.3))

model.add(Bidirectional(LSTM(512,return_sequences=True)))
'# model.add(SeqSelfAttention(attention_activation='sigmoid'))
model.add(Dense(256))
model.add(Dropout(0.3))

model.add(Flatten()) #Supposedly needed to fix stuff before dense layer
model.add(Dense(n_vocab))
model.add(Activation('softmax'))
model.compile(loss='categorical_crossentropy', optimizer='rmsprop')

**Comment by juyee1698** [comment]
Oh, I thought the error was related to flatten. I found the solution of replacing flatten with GlobalMaxPooling1D.
But I will definitely try this one too. Thanks!
